// libFuzzer harness for the aether-lite serial frame parser.
//
// Feeds fuzzer-generated bytes into al_parser_feed() one-at-a-time
// and in bulk, exercising every state-machine transition: sync
// detection, length accumulation, body reception, CRC validation,
// and timeout handling.

extern "C" {
#include "aether_lite_framing.h"
#include "aether_lite_dispatch.h"
#include "aether_lite_hal.h"
}

#include <cstdint>
#include <cstring>

// Minimal HAL stubs — the fuzzer only exercises the parser, not I/O.
static uint8_t s_txBuf[2048];
static size_t s_txPos;

static size_t stub_rx_read(uint8_t *, size_t, void *)
{
    return 0;
}

static int stub_tx_write(const uint8_t *buf, size_t len, void *)
{
    size_t room = sizeof(s_txBuf) - s_txPos;
    size_t n = (len < room) ? len : room;
    memcpy(s_txBuf + s_txPos, buf, n);
    s_txPos += n;
    return (n == len) ? 0 : -1;
}

static uint32_t s_tickMs;

static uint32_t stub_get_tick_ms(void)
{
    return s_tickMs;
}

// Dummy handler for dispatch testing
static int stub_handler(const uint8_t *, uint32_t,
                        uint8_t *resp, uint32_t resp_cap,
                        uint32_t *resp_len)
{
    (void)resp;
    (void)resp_cap;
    *resp_len = 0;
    return 0;
}

static al_method_entry_t s_methods[] = {
    {0, stub_handler},
};

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    if (size == 0)
        return 0;

    // Reset state for each input
    s_txPos = 0;
    s_tickMs = 1000;

    al_hal_t hal{};
    hal.rx_read = stub_rx_read;
    hal.tx_write = stub_tx_write;
    hal.get_tick_ms = stub_get_tick_ms;

    al_init(&hal);
    al_register_service(0x12345678u, s_methods, 1);

    // Strategy 1: Feed bytes one at a time (exercises every state transition)
    {
        al_parser_t parser{};
        for (size_t i = 0; i < size; ++i)
        {
            size_t consumed = 0;
            int complete = al_parser_feed(&parser, &data[i], 1, &consumed);
            if (complete)
            {
                (void)al_parser_frame_data();
            }
        }
    }

    // Strategy 2: Feed entire buffer at once (exercises bulk parsing)
    {
        al_parser_t parser{};
        size_t consumed = 0;
        al_parser_feed(&parser, data, size, &consumed);
    }

    return 0;
}
