// libFuzzer harness for FrameIO ring-buffer parser.
//
// Feeds fuzzer-generated bytes into an IpcRing, then attempts to read
// frames back out.  Exercises peekFrameHeader, readFrame, readFrameAlloc,
// and writeFrame with arbitrary header + payload combinations.

#include "FrameIO.h"
#include "Types.h"

#include <cstdint>
#include <cstring>
#include <memory>
#include <vector>

using namespace aether::ipc;

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    if (size == 0)
        return 0;

    auto ring = std::make_unique<IpcRing>();

    // Strategy 1: Write raw bytes into the ring, then try to parse frames.
    // This tests the read path with arbitrary ring contents.
    {
        uint32_t toWrite = static_cast<uint32_t>(
            std::min(size, static_cast<size_t>(ring->writeAvailable())));
        (void)ring->write(data, toWrite);

        FrameHeader hdr{};
        while (peekFrameHeader(ring.get(), &hdr))
        {
            if (hdr.payloadBytes > kMaxPayload)
            {
                // Corrupted header — skip the header bytes to avoid infinite loop
                (void)ring->skip(sizeof(FrameHeader));
                continue;
            }

            std::vector<uint8_t> payload;
            int rc = readFrameAlloc(ring.get(), &hdr, &payload);
            if (rc != IPC_SUCCESS)
                break;
        }
    }

    // Strategy 2: Interpret fuzzer input as a FrameHeader + payload and
    // round-trip through writeFrame → readFrame.
    if (size >= sizeof(FrameHeader))
    {
        auto ring2 = std::make_unique<IpcRing>();

        FrameHeader writeHdr{};
        std::memcpy(&writeHdr, data, sizeof(FrameHeader));

        const uint8_t *payload = data + sizeof(FrameHeader);
        uint32_t payloadLen = static_cast<uint32_t>(size - sizeof(FrameHeader));

        // Clamp to what writeFrame accepts
        if (payloadLen > kMaxPayload)
            payloadLen = kMaxPayload;

        writeHdr.payloadBytes = payloadLen;

        int wrc = writeFrame(ring2.get(), writeHdr, payload, payloadLen);
        if (wrc == IPC_SUCCESS)
        {
            FrameHeader readHdr{};
            std::vector<uint8_t> readPayload;
            readFrameAlloc(ring2.get(), &readHdr, &readPayload);
        }
    }

    return 0;
}
