"""
C API code emitter: generates C++ wrapper classes that call through aether_ipc.h.

Unlike the default C++ backend (which inherits from ServiceBase/ClientBase),
this backend generates standalone classes using the stable C API with opaque
handles.  The generated code only requires aether_ipc.h — no internal headers.

Each service produces four files:
  server/{Name}.h    — class with virtual handlers + opaque aether_service_t
  server/{Name}.cpp  — request dispatcher + notification senders
  client/{Name}.h    — class with typed RPC methods + opaque aether_client_t
  client/{Name}.cpp  — RPC marshaling + notification dispatcher
"""

from typing import Optional

from .parser import IdlFile
from .types import TYPE_MAP, cpp_type, fnv1a_32


def _resolve_type(idl_type: str, idl: IdlFile) -> str:
    if idl_type in TYPE_MAP:
        return cpp_type(idl_type)
    return idl_type


def _cpp_param_type(type_name: str, array_size: Optional[int], idl: IdlFile) -> str:
    base = _resolve_type(type_name, idl)
    if array_size is not None:
        return f"std::array<{base}, {array_size}>"
    return base


def _out_size_expr(p, idl: IdlFile) -> str:
    if p.type_name == "string":
        return str(p.array_size + 1)
    if p.array_size is not None:
        base = _resolve_type(p.type_name, idl)
        return f"{p.array_size} * sizeof({base})"
    return f"sizeof(*{p.name})"


def _param_decl(p, idl: IdlFile, is_out: bool = False) -> str:
    if p.type_name == "string":
        return f"char *{p.name}" if is_out else f"const char *{p.name}"
    if is_out:
        return f"{_resolve_type(p.type_name, idl)} *{p.name}"
    return f"{_cpp_param_type(p.type_name, p.array_size, idl)} {p.name}"


def _wire_size(p, idl: IdlFile) -> str:
    if p.type_name == "string":
        return str(p.array_size + 1)
    return f"sizeof({_cpp_param_type(p.type_name, p.array_size, idl)})"


def _has_non_string_arrays(items, direction_filter=None):
    for item in items:
        for p in item.params:
            if direction_filter and p.direction != direction_filter:
                continue
            if p.array_size is not None and p.type_name != "string":
                return True
    return False


def _emit_enums(w, idl: IdlFile):
    if idl.methods:
        w("")
        w("    enum MethodId : uint32_t")
        w("    {")
        for m in idl.methods:
            w(f"        k{m.name} = {m.method_id},")
        w("    };")

    if idl.notifications:
        w("")
        w("    enum NotifyId : uint32_t")
        w("    {")
        for n in idl.notifications:
            w(f"        k{n.name} = {n.notify_id},")
        w("    };")


# ── Server side ──────────────────────────────────────────────────────

def emit_c_api_server_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    has_arrays = _has_non_string_arrays(idl.methods + idl.notifications,
                                        direction_filter="in")

    w("// Auto-generated by ipcgen (c_api backend) — do not edit.")
    w("#pragma once")
    w('#include "aether_ipc.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    if has_arrays:
        w("#include <array>")
    w("#include <cstdint>")
    w("#include <cstdlib>")
    w("#include <cstring>")
    w("")
    w("namespace aether::ipc")
    w("{")
    w("")
    w(f"class {name}")
    w("{")
    w("public:")
    w(f"    explicit {name}(const char *serviceName);")
    w(f"    virtual ~{name}();")
    w("")
    w(f"    {name}(const {name} &) = delete;")
    w(f"    {name} &operator=(const {name} &) = delete;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")
    w("    bool start();")
    w("    void stop();")
    w("    bool isRunning() const;")
    w("")
    w("protected:")

    # Virtual handler declarations
    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        w(f"    virtual int handle{m.name}({', '.join(parts)}) = 0;")

    w("")

    # Notification sender declarations
    for n in idl.notifications:
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]
        w(f"    int send{n.name}({', '.join(parts)});")

    w("")
    w("private:")
    w("    aether_service_t m_svc = nullptr;")
    w("")
    w("    static int onRequestThunk(uint32_t service_id, uint32_t message_id,")
    w("                              const uint8_t *req, uint32_t req_len,")
    w("                              uint8_t **resp, uint32_t *resp_len,")
    w("                              void *user_data);")
    w("};")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


def emit_c_api_server_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen (c_api backend) — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace aether::ipc")
    w("{")

    # Constructor
    w("")
    w(f"{name}::{name}(const char *serviceName)")
    w("{")
    w("    aether_service_create(serviceName, onRequestThunk, this, &m_svc);")
    w("}")

    # Destructor
    w("")
    w(f"{name}::~{name}()")
    w("{")
    w("    if (m_svc) aether_service_destroy(m_svc);")
    w("}")

    # start / stop / isRunning
    w("")
    w(f"bool {name}::start()")
    w("{")
    w("    return m_svc && aether_service_start(m_svc) == AETHER_SUCCESS;")
    w("}")
    w("")
    w(f"void {name}::stop()")
    w("{")
    w("    if (m_svc) aether_service_stop(m_svc);")
    w("}")
    w("")
    w(f"bool {name}::isRunning() const")
    w("{")
    w("    return m_svc && aether_service_is_running(m_svc);")
    w("}")

    # Static thunk → dispatch
    w("")
    w(f"int {name}::onRequestThunk(uint32_t /*service_id*/, uint32_t message_id,")
    w( "                              const uint8_t *req, uint32_t req_len,")
    w( "                              uint8_t **resp, uint32_t *resp_len,")
    w( "                              void *user_data)")
    w("{")
    w(f"    auto *self = static_cast<{name} *>(user_data);")
    w("")
    w("    switch (message_id)")
    w("    {")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        w(f"    case {name}::k{m.name}:")
        w("    {")

        # Validate request size
        if in_params:
            size_parts = []
            for p in in_params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(_wire_size(p, idl))
            expected = " + ".join(size_parts)
            w(f"        if (req_len < {expected})")
            w("        {")
            w("            *resp = nullptr; *resp_len = 0;")
            w("            return AETHER_ERR_INVALID_ARGUMENT;")
            w("        }")

            # Unmarshal [in] params
            offset = 0
            for p in in_params:
                if p.type_name == "string":
                    w(f"        char {p.name}[{p.array_size + 1}];")
                    w(f"        std::memcpy({p.name}, req + {offset}, sizeof({p.name}));")
                    w(f"        {p.name}[{p.array_size}] = '\\0';")
                    sz = str(p.array_size + 1)
                else:
                    ct = _cpp_param_type(p.type_name, p.array_size, idl)
                    w(f"        {ct} {p.name};")
                    w(f"        std::memcpy(&{p.name}, req + {offset}, sizeof({p.name}));")
                    sz = f"sizeof({ct})"
                if offset == 0:
                    offset = sz
                else:
                    offset = f"{offset} + {sz}"

        # Declare [out] params (value-initialized)
        for p in out_params:
            if p.type_name == "string":
                w(f"        char {p.name}[{p.array_size + 1}] = {{}};")
            else:
                base = _resolve_type(p.type_name, idl)
                if p.array_size is not None:
                    w(f"        {base} {p.name}[{p.array_size}]{{}};")
                else:
                    w(f"        {base} {p.name}{{}};")

        # Call handler
        out_args = []
        for p in out_params:
            if p.type_name == "string" or p.array_size is not None:
                out_args.append(p.name)
            else:
                out_args.append(f"&{p.name}")
        call_args = [p.name for p in in_params] + out_args
        w(f"        int _rc = self->handle{m.name}({', '.join(call_args)});")

        # Marshal [out] params → malloc'd buffer
        if out_params:
            size_parts = [f"sizeof({p.name})" for p in out_params]
            total = " + ".join(size_parts)
            w(f"        *resp_len = {total};")
            w(f"        *resp = static_cast<uint8_t *>(std::malloc(*resp_len));")
            offset = "0"
            for i, p in enumerate(out_params):
                src = p.name if (p.type_name == "string" or p.array_size is not None) else f"&{p.name}"
                if i == 0:
                    w(f"        std::memcpy(*resp, {src}, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"        std::memcpy(*resp + {offset}, {src}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"
        else:
            w("        *resp = nullptr;")
            w("        *resp_len = 0;")

        w("        return _rc;")
        w("    }")

    w("    default:")
    w("        *resp = nullptr; *resp_len = 0;")
    w("        return AETHER_ERR_INVALID_METHOD;")
    w("    }")
    w("}")

    # Notification senders
    for n in idl.notifications:
        w("")
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]

        w(f"int {name}::send{n.name}({', '.join(parts)})")
        w("{")

        for p in n.params:
            if p.type_name == "string":
                w(f"    if ({p.name} == nullptr) return AETHER_ERR_INVALID_ARGUMENT;")

        if n.params:
            size_parts = []
            for p in n.params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(f"sizeof({p.name})")
            total = " + ".join(size_parts)
            w(f"    uint8_t payload[{total}];")
            offset = "0"
            for i, p in enumerate(n.params):
                if p.type_name == "string":
                    buf = f"_{p.name}"
                    w(f"    char {buf}[{p.array_size + 1}] = {{}};")
                    w(f"    std::strncpy({buf}, {p.name}, {p.array_size});")
                    sz = str(p.array_size + 1)
                    src = buf
                else:
                    sz = f"sizeof({p.name})"
                    src = f"&{p.name}"
                if i == 0:
                    w(f"    std::memcpy(payload, {src}, {sz});")
                    offset = sz
                else:
                    w(f"    std::memcpy(payload + {offset}, {src}, {sz});")
                    offset = f"{offset} + {sz}"
            w(f"    return aether_service_notify(m_svc, kServiceId, {name}::k{n.name},")
            w(f"                                 payload, sizeof(payload));")
        else:
            w(f"    return aether_service_notify(m_svc, kServiceId, {name}::k{n.name},")
            w( "                                 nullptr, 0);")

        w("}")

    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


# ── Client side ──────────────────────────────────────────────────────

def emit_c_api_client_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    has_arrays = _has_non_string_arrays(idl.methods + idl.notifications,
                                        direction_filter="in")

    w("// Auto-generated by ipcgen (c_api backend) — do not edit.")
    w("#pragma once")
    w('#include "aether_ipc.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    if has_arrays:
        w("#include <array>")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("")
    w("namespace aether::ipc")
    w("{")
    w("")
    w(f"class {name}")
    w("{")
    w("public:")
    w(f"    explicit {name}(const char *serviceName);")
    w(f"    virtual ~{name}();")
    w("")
    w(f"    {name}(const {name} &) = delete;")
    w(f"    {name} &operator=(const {name} &) = delete;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")
    w("    bool connect();")
    w("    void disconnect();")
    w("    bool isConnected() const;")
    w("")

    # Typed RPC method declarations
    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        parts.append("uint32_t timeoutMs = 2000")
        w(f"    int {m.name}({', '.join(parts)});")

    w("")
    w("protected:")

    # Notification callback declarations
    for n in idl.notifications:
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]
        w(f"    virtual void on{n.name}({', '.join(parts)}) {{}}")

    w("")
    w("private:")
    w("    aether_client_t m_cli = nullptr;")
    w("")
    w("    static void onNotifyThunk(uint32_t service_id, uint32_t message_id,")
    w("                              const uint8_t *payload, uint32_t len,")
    w("                              void *user_data);")
    w("};")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


def emit_c_api_client_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen (c_api backend) — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace aether::ipc")
    w("{")

    # Constructor
    w("")
    w(f"{name}::{name}(const char *serviceName)")
    w("{")
    w("    aether_client_create(serviceName, onNotifyThunk, this, &m_cli);")
    w("}")

    # Destructor
    w("")
    w(f"{name}::~{name}()")
    w("{")
    w("    if (m_cli) aether_client_destroy(m_cli);")
    w("}")

    # connect / disconnect / isConnected
    w("")
    w(f"bool {name}::connect()")
    w("{")
    w("    return m_cli && aether_client_connect(m_cli) == AETHER_SUCCESS;")
    w("}")
    w("")
    w(f"void {name}::disconnect()")
    w("{")
    w("    if (m_cli) aether_client_disconnect(m_cli);")
    w("}")
    w("")
    w(f"bool {name}::isConnected() const")
    w("{")
    w("    return m_cli && aether_client_is_connected(m_cli);")
    w("}")

    # Typed RPC methods
    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        parts.append("uint32_t timeoutMs")

        w("")
        w(f"int {name}::{m.name}({', '.join(parts)})")
        w("{")

        for p in in_params:
            if p.type_name == "string":
                w(f"    if ({p.name} == nullptr) return AETHER_ERR_INVALID_ARGUMENT;")

        # Marshal [in] params into a request buffer
        if in_params:
            size_parts = []
            for p in in_params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(f"sizeof({p.name})")
            w(f"    uint8_t req[{' + '.join(size_parts)}];")
            offset = "0"
            for i, p in enumerate(in_params):
                if p.type_name == "string":
                    buf = f"_{p.name}"
                    w(f"    char {buf}[{p.array_size + 1}] = {{}};")
                    w(f"    std::strncpy({buf}, {p.name}, {p.array_size});")
                    sz = str(p.array_size + 1)
                    src = buf
                else:
                    sz = f"sizeof({p.name})"
                    src = f"&{p.name}"
                if i == 0:
                    w(f"    std::memcpy(req, {src}, {sz});")
                    offset = sz
                else:
                    w(f"    std::memcpy(req + {offset}, {src}, {sz});")
                    offset = f"{offset} + {sz}"
        else:
            w("    const uint8_t *req = nullptr;")

        # Calculate response capacity
        if out_params:
            resp_size_parts = [_out_size_expr(p, idl) for p in out_params]
            resp_cap = " + ".join(resp_size_parts)
        else:
            resp_cap = "0"

        req_len = "sizeof(req)" if in_params else "0"

        w(f"    uint8_t resp[{resp_cap} > 0 ? {resp_cap} : 1];")
        w("    uint32_t resp_len = 0;")
        w(f"    int _rc = aether_client_call(m_cli, kServiceId, {name}::k{m.name},")
        w(f"                                 req, {req_len},")
        w(f"                                 resp, sizeof(resp), &resp_len, timeoutMs);")

        # Unmarshal [out] params
        if out_params:
            w("")
            size_parts = [_out_size_expr(p, idl) for p in out_params]
            w(f"    if (_rc == AETHER_SUCCESS && resp_len >= {' + '.join(size_parts)})")
            w("    {")
            offset = "0"
            for i, p in enumerate(out_params):
                sz = _out_size_expr(p, idl)
                if i == 0:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, resp, {sz});")
                    offset = sz
                else:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, resp + {offset}, {sz});")
                    offset = f"{offset} + {sz}"
            w("    }")

        w("    return _rc;")
        w("}")

    # Notification dispatch
    w("")
    w(f"void {name}::onNotifyThunk(uint32_t service_id, uint32_t message_id,")
    w( "                              const uint8_t *payload, uint32_t len,")
    w( "                              void *user_data)")
    w("{")
    w(f"    auto *self = static_cast<{name} *>(user_data);")
    w("    if (service_id != kServiceId) return;")
    w("")
    w("    switch (message_id)")
    w("    {")

    for n in idl.notifications:
        w(f"    case {name}::k{n.name}:")
        w("    {")

        if n.params:
            size_parts = []
            for p in n.params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(_wire_size(p, idl))
            expected = " + ".join(size_parts)
            w(f"        if (len < {expected}) break;")

        offset = "0"
        for i, p in enumerate(n.params):
            if p.type_name == "string":
                w(f"        char {p.name}[{p.array_size + 1}];")
                sz = str(p.array_size + 1)
                if i == 0:
                    w(f"        std::memcpy({p.name}, payload, {sz});")
                    offset = sz
                else:
                    w(f"        std::memcpy({p.name}, payload + {offset}, {sz});")
                    offset = f"{offset} + {sz}"
                w(f"        {p.name}[{p.array_size}] = '\\0';")
            else:
                ct = _cpp_param_type(p.type_name, p.array_size, idl)
                w(f"        {ct} {p.name};")
                if i == 0:
                    w(f"        std::memcpy(&{p.name}, payload, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"        std::memcpy(&{p.name}, payload + {offset}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"
        call_args = ", ".join(p.name for p in n.params)
        w(f"        self->on{n.name}({call_args});")
        w("        break;")
        w("    }")

    w("    default:")
    w("        break;")
    w("    }")
    w("}")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)
