"""
C++ code emitter: generates server and client source files from the AST.

Each service produces four files:
  server/{Name}.h    — class inheriting ServiceBase
  server/{Name}.cpp  — onRequest dispatch + notification senders
  client/{Name}.h    — class inheriting ClientBase
  client/{Name}.cpp  — typed RPC methods + onNotification dispatch
"""

from .parser import IdlFile
from .types import TYPE_MAP, cpp_type, fnv1a_32


def _resolve_type(idl_type: str, idl: IdlFile) -> str:
    """Map IDL type to C++. Built-ins go through TYPE_MAP; user types pass through."""
    if idl_type in TYPE_MAP:
        return cpp_type(idl_type)
    return idl_type  # user-defined enum/struct name is the same in C++


def _emit_enums(w, idl: IdlFile):
    """Emit MethodId and NotifyId enums into a class body."""
    if idl.methods:
        w("")
        w("    enum MethodId : uint32_t")
        w("    {")
        for m in idl.methods:
            w(f"        k{m.name} = {m.method_id},")
        w("    };")

    if idl.notifications:
        w("")
        w("    enum NotifyId : uint32_t")
        w("    {")
        for n in idl.notifications:
            w(f"        k{n.name} = {n.notify_id},")
        w("    };")


# ── Shared types header ──────────────────────────────────────────────

def emit_types_h(idl: IdlFile) -> str:
    """Generate a shared types header with enum and struct definitions."""
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    w("#include <cstdint>")
    w("")
    w("namespace ms::ipc")
    w("{")

    for enum_def in idl.enums:
        w("")
        w(f"enum {enum_def.name} : uint32_t")
        w("{")
        for val in enum_def.values:
            w(f"    {val.name} = {val.value},")
        w("};")

    for struct_def in idl.structs:
        w("")
        w(f"struct {struct_def.name}")
        w("{")
        for f in struct_def.fields:
            ct = _resolve_type(f.type_name, idl)
            w(f"    {ct} {f.name};")
        w("};")

    w("")
    w("} // namespace ms::ipc")
    w("")

    return "\n".join(lines)


# ── Server side ──────────────────────────────────────────────────────

def emit_server_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    w('#include "ServiceBase.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    w("#include <cstdint>")
    w("#include <cstring>")
    w("#include <vector>")
    w("")
    w("namespace ms::ipc")
    w("{")
    w("")
    w(f"class {name} : public ServiceBase")
    w("{")
    w("public:")
    w("    using ServiceBase::ServiceBase;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")
    w("protected:")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} {p.name}")
        for p in out_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} *{p.name}")
        w(f"    virtual int handle{m.name}({', '.join(parts)}) = 0;")

    w("")

    for n in idl.notifications:
        parts = [f"{_resolve_type(p.type_name, idl)} {p.name}" for p in n.params]
        w(f"    int notify{n.name}({', '.join(parts)});")

    w("")
    w("    int onRequest(uint32_t messageId, const std::vector<uint8_t> &request,")
    w("                  std::vector<uint8_t> *response) override;")
    w("};")
    w("")
    w("} // namespace ms::ipc")
    w("")

    return "\n".join(lines)


def emit_server_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace ms::ipc")
    w("{")
    w("")

    # onRequest dispatch
    w(f"int {name}::onRequest(uint32_t messageId,")
    pad = " " * len(f"int {name}::onRequest(")
    w(f"{pad}const std::vector<uint8_t> &request,")
    w(f"{pad}std::vector<uint8_t> *response)")
    w("{")
    w("    switch (messageId)")
    w("    {")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        w(f"    case {name}::k{m.name}:")
        w("    {")

        # Unmarshal [in] params
        if in_params:
            offset = 0
            for p in in_params:
                ct = _resolve_type(p.type_name, idl)
                w(f"        {ct} {p.name};")
                w(f"        std::memcpy(&{p.name}, request.data() + {offset}, sizeof({p.name}));")
                if offset == 0:
                    offset = f"sizeof({ct})"
                else:
                    offset = f"{offset} + sizeof({ct})"

        # Declare [out] params
        for p in out_params:
            w(f"        {_resolve_type(p.type_name, idl)} {p.name};")

        # Call handler
        call_args = [p.name for p in in_params] + [f"&{p.name}" for p in out_params]
        w(f"        int _rc = handle{m.name}({', '.join(call_args)});")

        # Marshal [out] params
        if out_params:
            size_parts = [f"sizeof({p.name})" for p in out_params]
            w(f"        response->resize({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(out_params):
                if i == 0:
                    w(f"        std::memcpy(response->data(), &{p.name}, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"        std::memcpy(response->data() + {offset}, &{p.name}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"

        w("        return _rc;")
        w("    }")

    w("    default:")
    w("        return IPC_ERR_INVALID_METHOD;")
    w("    }")
    w("}")

    # Notification senders
    for n in idl.notifications:
        w("")
        parts = [f"{_resolve_type(p.type_name, idl)} {p.name}" for p in n.params]

        w(f"int {name}::notify{n.name}({', '.join(parts)})")
        w("{")

        if n.params:
            size_parts = [f"sizeof({p.name})" for p in n.params]
            w(f"    std::vector<uint8_t> payload({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(n.params):
                if i == 0:
                    w(f"    std::memcpy(payload.data(), &{p.name}, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"    std::memcpy(payload.data() + {offset}, &{p.name}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"
            w(f"    return sendNotify(kServiceId, {name}::k{n.name}, payload.data(),")
            w("                      static_cast<uint32_t>(payload.size()));")
        else:
            w(f"    return sendNotify(kServiceId, {name}::k{n.name}, nullptr, 0);")

        w("}")

    w("")
    w("} // namespace ms::ipc")
    w("")

    return "\n".join(lines)


# ── Client side ──────────────────────────────────────────────────────

def emit_client_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    w('#include "ClientBase.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    w("#include <cstdint>")
    w("#include <cstring>")
    w("#include <vector>")
    w("")
    w("namespace ms::ipc")
    w("{")
    w("")
    w(f"class {name} : public ClientBase")
    w("{")
    w("public:")
    w("    using ClientBase::ClientBase;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} {p.name}")
        for p in out_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} *{p.name}")
        parts.append("uint32_t timeoutMs = 2000")
        w(f"    int {m.name}({', '.join(parts)});")

    w("")
    w("protected:")

    for n in idl.notifications:
        parts = [f"{_resolve_type(p.type_name, idl)} {p.name}" for p in n.params]
        w(f"    virtual void on{n.name}({', '.join(parts)}) {{}}")

    w("")
    w("    void onNotification(uint32_t serviceId, uint32_t messageId,")
    w("                        const std::vector<uint8_t> &payload) override;")
    w("};")
    w("")
    w("} // namespace ms::ipc")
    w("")

    return "\n".join(lines)


def emit_client_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace ms::ipc")
    w("{")

    # Typed RPC methods
    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        parts = []
        for p in in_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} {p.name}")
        for p in out_params:
            parts.append(f"{_resolve_type(p.type_name, idl)} *{p.name}")
        parts.append("uint32_t timeoutMs")

        w("")
        w(f"int {name}::{m.name}({', '.join(parts)})")
        w("{")

        # Marshal [in] params
        if in_params:
            size_parts = [f"sizeof({p.name})" for p in in_params]
            w(f"    std::vector<uint8_t> request({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(in_params):
                if i == 0:
                    w(f"    std::memcpy(request.data(), &{p.name}, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"    std::memcpy(request.data() + {offset}, &{p.name}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"
        else:
            w("    std::vector<uint8_t> request;")

        w("")
        w("    std::vector<uint8_t> response;")
        w(f"    int _rc = call(kServiceId, {name}::k{m.name}, request, &response, timeoutMs);")

        # Unmarshal [out] params
        if out_params:
            w("")
            size_parts = [f"sizeof(*{p.name})" for p in out_params]
            w(f"    if (_rc == IPC_SUCCESS && response.size() >= {' + '.join(size_parts)})")
            w("    {")
            offset = "0"
            for i, p in enumerate(out_params):
                if i == 0:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, response.data(), sizeof(*{p.name}));")
                    offset = f"sizeof(*{p.name})"
                else:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, response.data() + {offset}, sizeof(*{p.name}));")
                    offset = f"{offset} + sizeof(*{p.name})"
            w("    }")

        w("    return _rc;")
        w("}")

    # onNotification dispatch
    w("")
    w(f"void {name}::onNotification(uint32_t serviceId, uint32_t messageId,")
    pad = " " * len(f"void {name}::onNotification(")
    w(f"{pad}const std::vector<uint8_t> &payload)")
    w("{")
    w("    if (serviceId != kServiceId) return;")
    w("")
    w("    switch (messageId)")
    w("    {")

    for n in idl.notifications:
        w(f"    case {name}::k{n.name}:")
        w("    {")
        offset = "0"
        for i, p in enumerate(n.params):
            ct = _resolve_type(p.type_name, idl)
            w(f"        {ct} {p.name};")
            if i == 0:
                w(f"        std::memcpy(&{p.name}, payload.data(), sizeof({p.name}));")
                offset = f"sizeof({p.name})"
            else:
                w(f"        std::memcpy(&{p.name}, payload.data() + {offset}, sizeof({p.name}));")
                offset = f"{offset} + sizeof({p.name})"
        call_args = ", ".join(p.name for p in n.params)
        w(f"        on{n.name}({call_args});")
        w("        break;")
        w("    }")

    w("    default:")
    w("        break;")
    w("    }")
    w("}")
    w("")
    w("} // namespace ms::ipc")
    w("")

    return "\n".join(lines)
