"""
C++ code emitter: generates server and client source files from the AST.

Each service produces four files:
  server/{Name}.h    — class inheriting ServiceBase
  server/{Name}.cpp  — onRequest dispatch + notification senders
  client/{Name}.h    — class inheriting ClientBase
  client/{Name}.cpp  — typed RPC methods + onNotification dispatch
"""

from typing import Optional

from .parser import IdlFile
from .types import TYPE_MAP, cpp_type, fnv1a_32


def _resolve_type(idl_type: str, idl: IdlFile) -> str:
    """Map IDL type to C++. Built-ins go through TYPE_MAP; user types pass through."""
    if idl_type in TYPE_MAP:
        return cpp_type(idl_type)
    return idl_type  # user-defined enum/struct name is the same in C++


def _cpp_param_type(type_name: str, array_size: Optional[int], idl: IdlFile) -> str:
    """Full C++ type, wrapping in std::array<> when array_size is set.
    Not used for string types — use _param_decl() instead."""
    base = _resolve_type(type_name, idl)
    if array_size is not None:
        return f"std::array<{base}, {array_size}>"
    return base


def _out_size_expr(p, idl: IdlFile) -> str:
    """Byte-size expression for an [out] param in generated C++."""
    if p.type_name == "string":
        return str(p.array_size + 1)
    if p.array_size is not None:
        base = _resolve_type(p.type_name, idl)
        return f"{p.array_size} * sizeof({base})"
    return f"sizeof(*{p.name})"


def _param_decl(p, idl: IdlFile, is_out: bool = False) -> str:
    """Full C++ parameter declaration (type + name) for a method/notification param."""
    if p.type_name == "string":
        return f"char *{p.name}" if is_out else f"const char *{p.name}"
    if is_out:
        return f"{_resolve_type(p.type_name, idl)} *{p.name}"
    return f"{_cpp_param_type(p.type_name, p.array_size, idl)} {p.name}"


def _wire_size(p, idl: IdlFile) -> str:
    """C++ size expression for a param's wire representation."""
    if p.type_name == "string":
        return str(p.array_size + 1)
    return f"sizeof({_cpp_param_type(p.type_name, p.array_size, idl)})"


def _emit_enums(w, idl: IdlFile):
    """Emit MethodId and NotifyId enums into a class body."""
    if idl.methods:
        w("")
        w("    enum MethodId : uint32_t")
        w("    {")
        for m in idl.methods:
            w(f"        k{m.name} = {m.method_id},")
        w("    };")

    if idl.notifications:
        w("")
        w("    enum NotifyId : uint32_t")
        w("    {")
        for n in idl.notifications:
            w(f"        k{n.name} = {n.notify_id},")
        w("    };")


def _has_non_string_arrays(items, direction_filter=None):
    """Check if any param in items has an array that isn't a string."""
    for item in items:
        for p in item.params:
            if direction_filter and p.direction != direction_filter:
                continue
            if p.array_size is not None and p.type_name != "string":
                return True
    return False


# ── Shared types header ──────────────────────────────────────────────

def emit_types_h(idl: IdlFile) -> str:
    """Generate a shared types header with enum and struct definitions."""
    name = idl.service_name
    lines = []
    w = lines.append

    has_arrays = any(f.array_size is not None and f.type_name != "string"
                     for s in idl.structs for f in s.fields)

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    if has_arrays:
        w("#include <array>")
    w("#include <cstdint>")
    w("")
    w("namespace aether::ipc")
    w("{")

    for enum_def in idl.enums:
        w("")
        w(f"enum {enum_def.name} : uint32_t")
        w("{")
        for val in enum_def.values:
            w(f"    {val.name} = {val.value},")
        w("};")

    for struct_def in idl.structs:
        w("")
        w(f"struct {struct_def.name}")
        w("{")
        for f in struct_def.fields:
            if f.type_name == "string":
                w(f"    char {f.name}[{f.array_size + 1}];")
            else:
                ct = _cpp_param_type(f.type_name, f.array_size, idl)
                w(f"    {ct} {f.name};")
        w("};")

    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


# ── Server side ──────────────────────────────────────────────────────

def emit_server_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    # Only non-string [in] params use std::array in signatures.
    has_arrays = _has_non_string_arrays(idl.methods + idl.notifications,
                                        direction_filter="in")

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    w('#include "ServiceBase.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    if has_arrays:
        w("#include <array>")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("#include <vector>")
    w("")
    w("namespace aether::ipc")
    w("{")
    w("")
    w(f"class {name} : public ServiceBase")
    w("{")
    w("public:")
    w("    using ServiceBase::ServiceBase;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")
    w("protected:")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        w(f"    virtual int handle{m.name}({', '.join(parts)}) = 0;")

    w("")

    for n in idl.notifications:
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]
        w(f"    int notify{n.name}({', '.join(parts)});")

    w("")
    w("    int onRequest(uint32_t messageId, const std::vector<uint8_t> &request,")
    w("                  std::vector<uint8_t> *response) override;")
    w("};")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


def emit_server_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace aether::ipc")
    w("{")
    w("")

    # onRequest dispatch
    w(f"int {name}::onRequest(uint32_t messageId,")
    pad = " " * len(f"int {name}::onRequest(")
    w(f"{pad}const std::vector<uint8_t> &request,")
    w(f"{pad}std::vector<uint8_t> *response)")
    w("{")
    w("    switch (messageId)")
    w("    {")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        w(f"    case {name}::k{m.name}:")
        w("    {")

        # Unmarshal [in] params — validate request size first.
        if in_params:
            size_parts = []
            for p in in_params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(_wire_size(p, idl))
            expected = " + ".join(size_parts)
            w(f"        if (request.size() < {expected})")
            w( "            return IPC_ERR_INVALID_METHOD;")
            offset = 0
            for p in in_params:
                if p.type_name == "string":
                    w(f"        char {p.name}[{p.array_size + 1}];")
                    w(f"        std::memcpy({p.name}, request.data() + {offset}, sizeof({p.name}));")
                    w(f"        {p.name}[{p.array_size}] = '\\0';")
                    sz = str(p.array_size + 1)
                else:
                    ct = _cpp_param_type(p.type_name, p.array_size, idl)
                    w(f"        {ct} {p.name};")
                    w(f"        std::memcpy(&{p.name}, request.data() + {offset}, sizeof({p.name}));")
                    sz = f"sizeof({ct})"
                if offset == 0:
                    offset = sz
                else:
                    offset = f"{offset} + {sz}"

        # Declare [out] params — value-initialized to avoid leaking
        # uninitialized data if the handler returns an error.
        for p in out_params:
            if p.type_name == "string":
                w(f"        char {p.name}[{p.array_size + 1}] = {{}};")
            else:
                base = _resolve_type(p.type_name, idl)
                if p.array_size is not None:
                    w(f"        {base} {p.name}[{p.array_size}]{{}};")
                else:
                    w(f"        {base} {p.name}{{}};")


        # Call handler — strings and arrays decay to pointer, scalars use &.
        out_args = []
        for p in out_params:
            if p.type_name == "string" or p.array_size is not None:
                out_args.append(p.name)
            else:
                out_args.append(f"&{p.name}")
        call_args = [p.name for p in in_params] + out_args
        w(f"        int _rc = handle{m.name}({', '.join(call_args)});")

        # Marshal [out] params
        if out_params:
            size_parts = [f"sizeof({p.name})" for p in out_params]
            w(f"        response->resize({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(out_params):
                src = p.name if (p.type_name == "string" or p.array_size is not None) else f"&{p.name}"
                if i == 0:
                    w(f"        std::memcpy(response->data(), {src}, sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"        std::memcpy(response->data() + {offset}, {src}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"

        w("        return _rc;")
        w("    }")

    w("    default:")
    w("        return IPC_ERR_INVALID_METHOD;")
    w("    }")
    w("}")

    # Notification senders
    for n in idl.notifications:
        w("")
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]

        w(f"int {name}::notify{n.name}({', '.join(parts)})")
        w("{")

        for p in n.params:
            if p.type_name == "string":
                w(f"    if ({p.name} == nullptr) return IPC_ERR_INVALID_ARGUMENT;")

        if n.params:
            size_parts = []
            for p in n.params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(f"sizeof({p.name})")
            w(f"    std::vector<uint8_t> payload({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(n.params):
                if p.type_name == "string":
                    buf = f"_{p.name}"
                    w(f"    char {buf}[{p.array_size + 1}] = {{}};")
                    w(f"    std::strncpy({buf}, {p.name}, {p.array_size});")
                    sz = str(p.array_size + 1)
                    src = buf
                else:
                    sz = f"sizeof({p.name})"
                    src = f"&{p.name}"
                if i == 0:
                    w(f"    std::memcpy(payload.data(), {src}, {sz});")
                    offset = sz
                else:
                    w(f"    std::memcpy(payload.data() + {offset}, {src}, {sz});")
                    offset = f"{offset} + {sz}"
            w(f"    return sendNotify(kServiceId, {name}::k{n.name}, payload.data(),")
            w("                      static_cast<uint32_t>(payload.size()));")
        else:
            w(f"    return sendNotify(kServiceId, {name}::k{n.name}, nullptr, 0);")

        w("}")

    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


# ── Client side ──────────────────────────────────────────────────────

def emit_client_h(idl: IdlFile) -> str:
    name = idl.service_name
    service_id = fnv1a_32(name)
    lines = []
    w = lines.append

    # Only non-string [in] params use std::array in signatures.
    has_arrays = _has_non_string_arrays(idl.methods + idl.notifications,
                                        direction_filter="in")

    w("// Auto-generated by ipcgen — do not edit.")
    w("#pragma once")
    w('#include "ClientBase.h"')
    if idl.enums or idl.structs:
        w(f'#include "{name}Types.h"')
    if has_arrays:
        w("#include <array>")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("#include <vector>")
    w("")
    w("namespace aether::ipc")
    w("{")
    w("")
    w(f"class {name} : public ClientBase")
    w("{")
    w("public:")
    w("    using ClientBase::ClientBase;")
    w("")
    w(f"    static constexpr uint32_t kServiceId = 0x{service_id:08x}u;")

    _emit_enums(w, idl)

    w("")

    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]
        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        parts.append("uint32_t timeoutMs = 2000")
        w(f"    int {m.name}({', '.join(parts)});")

    w("")
    w("protected:")

    for n in idl.notifications:
        parts = [_param_decl(p, idl, is_out=False) for p in n.params]
        w(f"    virtual void on{n.name}({', '.join(parts)}) {{}}")

    w("")
    w("    void onNotification(uint32_t serviceId, uint32_t messageId,")
    w("                        const std::vector<uint8_t> &payload) override;")
    w("};")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)


def emit_client_cpp(idl: IdlFile) -> str:
    name = idl.service_name
    lines = []
    w = lines.append

    w("// Auto-generated by ipcgen — do not edit.")
    w(f'#include "{name}.h"')
    w("")
    w("namespace aether::ipc")
    w("{")

    # Typed RPC methods
    for m in idl.methods:
        in_params = [p for p in m.params if p.direction == "in"]
        out_params = [p for p in m.params if p.direction == "out"]

        parts = []
        for p in in_params:
            parts.append(_param_decl(p, idl, is_out=False))
        for p in out_params:
            parts.append(_param_decl(p, idl, is_out=True))
        parts.append("uint32_t timeoutMs")

        w("")
        w(f"int {name}::{m.name}({', '.join(parts)})")
        w("{")

        for p in in_params:
            if p.type_name == "string":
                w(f"    if ({p.name} == nullptr) return IPC_ERR_INVALID_ARGUMENT;")

        # Marshal [in] params
        if in_params:
            size_parts = []
            for p in in_params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(f"sizeof({p.name})")
            w(f"    std::vector<uint8_t> request({' + '.join(size_parts)});")
            offset = "0"
            for i, p in enumerate(in_params):
                if p.type_name == "string":
                    buf = f"_{p.name}"
                    w(f"    char {buf}[{p.array_size + 1}] = {{}};")
                    w(f"    std::strncpy({buf}, {p.name}, {p.array_size});")
                    sz = str(p.array_size + 1)
                    src = buf
                else:
                    sz = f"sizeof({p.name})"
                    src = f"&{p.name}"
                if i == 0:
                    w(f"    std::memcpy(request.data(), {src}, {sz});")
                    offset = sz
                else:
                    w(f"    std::memcpy(request.data() + {offset}, {src}, {sz});")
                    offset = f"{offset} + {sz}"
        else:
            w("    std::vector<uint8_t> request;")

        w("")
        w("    std::vector<uint8_t> response;")
        w(f"    int _rc = call(kServiceId, {name}::k{m.name}, request, &response, timeoutMs);")

        # Unmarshal [out] params
        if out_params:
            w("")
            size_parts = [_out_size_expr(p, idl) for p in out_params]
            w(f"    if (_rc == IPC_SUCCESS && response.size() >= {' + '.join(size_parts)})")
            w("    {")
            offset = "0"
            for i, p in enumerate(out_params):
                sz = _out_size_expr(p, idl)
                if i == 0:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, response.data(), {sz});")
                    offset = sz
                else:
                    w(f"        if ({p.name})")
                    w(f"            std::memcpy({p.name}, response.data() + {offset}, {sz});")
                    offset = f"{offset} + {sz}"
            w("    }")

        w("    return _rc;")
        w("}")

    # onNotification dispatch
    w("")
    w(f"void {name}::onNotification(uint32_t serviceId, uint32_t messageId,")
    pad = " " * len(f"void {name}::onNotification(")
    w(f"{pad}const std::vector<uint8_t> &payload)")
    w("{")
    w("    if (serviceId != kServiceId) return;")
    w("")
    w("    switch (messageId)")
    w("    {")

    for n in idl.notifications:
        w(f"    case {name}::k{n.name}:")
        w("    {")

        # Compute expected payload size and guard against truncated frames.
        if n.params:
            size_parts = []
            for p in n.params:
                if p.type_name == "string":
                    size_parts.append(str(p.array_size + 1))
                else:
                    size_parts.append(_wire_size(p, idl))
            expected = " + ".join(size_parts)
            w(f"        if (payload.size() < {expected}) break;")

        offset = "0"
        for i, p in enumerate(n.params):
            if p.type_name == "string":
                w(f"        char {p.name}[{p.array_size + 1}];")
                sz = str(p.array_size + 1)
                if i == 0:
                    w(f"        std::memcpy({p.name}, payload.data(), {sz});")
                    offset = sz
                else:
                    w(f"        std::memcpy({p.name}, payload.data() + {offset}, {sz});")
                    offset = f"{offset} + {sz}"
                w(f"        {p.name}[{p.array_size}] = '\\0';")
            else:
                ct = _cpp_param_type(p.type_name, p.array_size, idl)
                w(f"        {ct} {p.name};")
                if i == 0:
                    w(f"        std::memcpy(&{p.name}, payload.data(), sizeof({p.name}));")
                    offset = f"sizeof({p.name})"
                else:
                    w(f"        std::memcpy(&{p.name}, payload.data() + {offset}, sizeof({p.name}));")
                    offset = f"{offset} + sizeof({p.name})"
        call_args = ", ".join(p.name for p in n.params)
        w(f"        on{n.name}({call_args});")
        w("        break;")
        w("    }")

    w("    default:")
    w("        break;")
    w("    }")
    w("}")
    w("")
    w("} // namespace aether::ipc")
    w("")

    return "\n".join(lines)
